server:
  port: 8002

spring:
  application:
    name: rexyn-feign-test


eureka:

  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/

  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

