server:
  port: 9001

spring:
  application:
    name: rexyn-base

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.210:3306/rexyn_base?characterEncoding=utf-8
    username: root
    password: root

  jpa:
    database: mysql
    show-sql: true
  redis:
    host: 192.168.199.210
  rabbitmq:
    host: 192.168.199.210

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
  instance:
    prefer-ip-address: true




