server: 
  port: 9002
spring: 
  application:  
    name: rexyn-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.199.210:3306/rexyn_user?characterEncoding=utf-8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true

  redis:
    host: 192.168.199.210

  rabbitmq:
    host: 192.168.199.210

jwt:
  config:
    key: rexyn
    ttl: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
  instance:
    prefer-ip-address: true